### PR TITLE
fix: Consolidating Primitive and SupportFunction.

### PR DESCRIPTION
**Pull request by Rhuagh**
This change is [Reviewable](https://reviewable.io/reviews/kvark/collision-rs/63)

### CODE REVIEW

**Comment by Rhuagh** [comment]
The point is intricately tied to the implementation of the trait, not to the usage of the trait, therefore it should be an associated type imho.

**Comment by torkleyy** [comment]
I think there's something else to consider when discussing type parameters vs associated types. From the implementors perspective, an associated type is different from a type parameter in that it is not involved in the type construction. That means `Foo` with an associated `Bar` can only have one implementation for a given type, while `Foo<B>` does not have that restriction.

Logically, a pimitive has one concrete point type, thus I think associated types make more sense here.

**Comment by torkleyy** [comment]
Ah, didn't see your comment @Rhuagh

**Comment by kvark** [comment]
Okey you language semantics snobs, shipit!
bors r+

**Pull request merged**
